# Generated by Django 2.2.3 on 2019-08-01 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PariSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cagnote', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coteEquip1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('miseEquip1', models.DecimalField(decimal_places=2, max_digits=7)),
                ('coteEquip2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('miseEquip2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gainEquip1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficeEquip1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gainEquip2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficeEquip2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
